### ISSUE TITLE
`jenkins` ruleset fails with Jenkinsfiles containing classes when using Groovy 4.x

### ISSUE THREAD

**Issue by nre-ableton** [CodeNarc/CodeNarc#784]
I maintain a handful of Jenkinsfiles that use classes as a way to maintain structure. Such classes need to be declared `class Whatever extends WorkflowScript`, or else they won't be able to call pipeline steps from Jenkins. These Jenkinsfiles fail with the new `jenkins` ruleset introduced in CodeNarc 3.5.0, but _only_ when using Groovy 4.0.22. With Groovy 3.0.22, they work fine. CodeNarc's (abbreviated) output looks something like this:

```
WARNING org.codenarc.source.AbstractSourceCode - WARNING: Compilation error for non-default compiler phase (semantic analysis). Consider removing "enhanced" rules from your ruleset.
WARNING org.codenarc.source.AbstractSourceCode - Compilation failed for [CustomCompilerPhaseSourceDecorator[SourceFile[/home/nre/Code/<redacted>/./Jenkinsfile]]; phase=4 (semantic analysis)]; org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WARNING None: 14: unable to resolve class WorkflowScript
WARNING  @ line 14, column 1.
WARNING    class CommonStages extends WorkflowScript {
WARNING    ^
WARNING 1 error
WARNING .
```

As a potential hint, I've also noticed that some Jenkinsfiles with `import` statements fail in a similar manner:

```
WARNING org.codenarc.source.AbstractSourceCode - WARNING: Compilation error for non-default compiler phase (semantic analysis). Consider removing "enhanced" rules from your ruleset.
WARNING org.codenarc.source.AbstractSourceCode - Compilation failed for [CustomCompilerPhaseSourceDecorator[SourceFile[/home/nre/Code/<redacted>/./Jenkinsfile]]; phase=4 (semantic analysis)]; org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WARNING None: 5: unable to resolve class net.sf.json.JSONObject
WARNING  @ line 5, column 1.
WARNING    import net.sf.json.JSONObject
WARNING    ^
```

Again, this also works fine with Groovy 3.0.22. Although I don't think this should matter, I'm using JDK 21 in both instances, but have also tried with JDK 17 and got the same results.

**Comment by chrismair** [comment]
Are those Jenkins classes/imports on your classpath that is running CodeNarc? e.g. WorkflowScript and JSONObject?

The enhanced rules require all referenced classes within the code to be on the classpath, unlike "regular" rules.

**Comment by nre-ableton** [comment]
> Are those Jenkins classes/imports on your classpath that is running CodeNarc? e.g. WorkflowScript and JSONObject?
> 
> 
> 
> The enhanced rules require all referenced classes within the code to be on the classpath, unlike "regular" rules.

I can double-check this next time I'm at my computer. But I'm guessing not, IIRC we don't depend on the pipeline lib jars. I guess we'll need to do that. However, I'm still confused as to why this isn't a problem with Groovy 3.x.

**Comment by nre-ableton** [comment]
An update: `groovylint` has dependencies on the following JARs:

- Groovy's `lib` folder
- `CodeNarc`
- `GMetrics`
- `activation`
- `jaxb-api`
- `slf4j-api`
- `slf4j-simple`

I spent a bit of time last week trying to add dependencies on various Jenkins plugin JARs, but I couldn't find the ones that define `WorkflowScript`. It's not at all obvious to me which library actually defines that class. I'll keep poking around with this when I get some time, but if anyone knows offhand or could point me in the right direction, it would be much appreciated.
