### ISSUE TITLE
CodeNarc 1.6 and CustomCompilerPhaseSourceDecorator errors

### ISSUE THREAD

**Issue by tlefevre** [CodeNarc/CodeNarc#523]
Since upgrading to 1.6 I have gotten a lot of errors for the mentioned class.

Example:

```
Compilation failed for [CustomCompilerPhaseSourceDecorator[SourceFile[/home/thomas/.../SomethingSpec.groovy]]]; org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
None: 5: unable to resolve class grails.plugins.rest.client.RestResponse
 @ line 5, column 1.
   import grails.plugins.rest.client.RestResponse
   ^

None: 4: unable to resolve class grails.plugins.rest.client.RestBuilder
 @ line 4, column 1.
   import grails.plugins.rest.client.RestBuilder
   ^

None: 6: unable to resolve class spock.lang.Specification
 @ line 6, column 1.
   import spock.lang.Specification
```

Am I doing something wrong in regards to the new release?

**Comment by chrismair** [comment]
This looks to be due to one of the "[enhanced](https://codenarc.github.io/CodeNarc/codenarc-enhanced-classpath-rules.html)" rules being run against your source code, but you do not have the (required) project classes on the classpath. I can't tell from the above which rule it is, but since you say it started with CodeNarc 1.6, my guess would be the new **GrailsDomainGormMethods** rule, since that is an enhanced rule. So perhaps you are including the entire "grails" ruleset? If so, [exclude](https://codenarc.github.io/CodeNarc/codenarc-configuring-rules.html#turning-off-a-rule) that rule.

**Comment by tlefevre** [comment]
Ah, it didn't even occur to me - I haven't really dabbled in those rules yet I just added GrailsDomainGormMethods to the ruleset without realizing it was an enhanced rule. 

I tried to make the codenarc configuration in Gradle extend from the testCompile configuration, which made all the dependencies appear. Like so:

```
configurations {
    codenarc.extendsFrom testImplementation
}
```

Doesn't seem to work, there's still a ton of compilation errors. I went from 1900 something to 900 something. Still a lot of errors.

E.g.

unable to resolve class org.apache.http.entity.ContentType
unable to resolve class spock.lang.Shared

But org.spockframework:spock-core:1.3-groovy-2.5 is on the classpath. 

Do you have any experience with making the enhanced rules in a Gradle setup?

**Comment by erdi** [comment]
There's an example in this [integration test](https://github.com/CodeNarc/CodeNarc/blob/master/integration-test/src/test/groovy/org/codenarc/gradle/GradlePluginCompilationClasspathTest.groovy#L55). 

The thing is that you need to configure `compilationClasspath` property of CodeNarc tasks and not the `codenarc` dependency configuration. Also, because each class is compiled in isolation by CodeNarc what is in that integration test is not sufficient if more than one class is being analysed and they reference each other. In that case you will need to also add results of compiling the source set to the classpath used for CodeNarc analysis:
```
compilationClasspath = sourceSets.main.compileClasspath + sourceSets.main.output
```

**Comment by tlefevre** [comment]
Ah, thanks a bunch - I was looking around trying to find any documentation on how to approach it but failed. I'll give it a shot!

**Comment by tlefevre** [comment]
Good progress, I have now eliminated most of the compilation errors but seem to persist. They're all of a very specific type though:

None: Could not find class for Transformation Processor org.grails.datastore.gorm.services.transform.ServiceTransformation declared by grails.gorm.services.Service

All are of a "Transformation Processor" type.

What is the effect of a compilation failure? Does that mean the class can't be analyzed?

**Comment by erdi** [comment]
It means that it cannot be analysed by any of the enhanced rules. Regular rules will still be able to analyse the class as long as the class is able to be processed up to the default compilation phase used by CodeNarc which is `org.codehaus.groovy.control.Phases#CONVERSION` and in general as long as there is no syntax error in the class it will be able to be processed up to that phase.

**Comment by tlefevre** [comment]
Okay, that's what I expected. 

Do you have any ideas if there's a way to fix these issues or is there a general problem with the compiler and these transformation processors?

**Comment by erdi** [comment]
Sorry, I have no idea what these errors are about, I'm not a Grails user nowadays.

**Comment by tlefevre** [comment]
It seems like it's a Groovy compiler thing, it's trying to find these classes because they're supposed to do the AST transformations for grails / gorm annotations. So it seems like a general problem.

I'm guessing if it gains more traction because of other AST transformations we might get someone more capable to look at it :)

**Comment by sbglasius** [comment]
@tlefevre I actually managed to get it running on Grails 4 integration-test phase, but I have one weird issue. The gradle config is here:
```
tasks.withType(CodeNarc) {
    compilationClasspath += files(sourceSets.collectMany { SourceSet s ->
        [s.runtimeClasspath]
    })
    if(sourceSets.find { it.name == 'integrationTest'}) {
        codenarcClasspath += sourceSets.integrationTest.runtimeClasspath
    }
}
```
but the weird issue is, that I see this in all my `src/main` files:

![image](https://user-images.githubusercontent.com/625868/119795998-47664f00-bed9-11eb-92eb-87d6d54fe89a.png)
